# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy docker image - silvestre-website

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get version from csproj
      id: version
      run: |
        $xml=[xml](Get-Content .\Silvestre.App.Web.csproj)
        $version=$xml.Project.PropertyGroup.Version
        echo "project_version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh
      working-directory: src/Silvestre.App.Web
    - name: Print version
      run: echo "The version is ${{ steps.version.outputs.project_version }}"
    - name: Build the Docker image
      run: |
        SHOULD_PUBLISH='true'
        VERSION_SUFFIX=""
        if [[ "$GITHUB_REF" == refs/heads/* ]]; then
          if [ "$GITHUB_REF_NAME" == "master" ]; then
            VERSION_SUFFIX=""
          elif [ "$GITHUB_REF_NAME" == "dev" ]; then
            VERSION_SUFFIX="-dev"
          else
            SHOULD_PUBLISH='false'
          fi
        else
          SHOULD_PUBLISH='false'
        fi
        echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
        echo "SHOULD_PUBLISH=$SHOULD_PUBLISH" >> $GITHUB_ENV
        docker buildx build --platform linux/amd64,linux/arm64/v8 -f src/Silvestre.App.Web/Dockerfile --tag ghcr.io/paletas/personal-website:${{ steps.version.outputs.project_version }}${VERSION_SUFFIX} --tag ghcr.io/paletas/personal-website:$(echo ${{ steps.version.outputs.project_version }} | cut -d. -f1,2)${VERSION_SUFFIX} .
    - name: Log into GitHub Container Registry
      if: env.SHOULD_PUBLISH == 'true'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push Docker image
      if: env.SHOULD_PUBLISH == 'true'
      run: |
        docker push ghcr.io/paletas/personal-website:${{ steps.version.outputs.project_version }}${VERSION_SUFFIX}
        docker push ghcr.io/paletas/personal-website:$(echo ${{ steps.version.outputs.project_version }} | cut -d. -f1,2)${VERSION_SUFFIX}
      env:
        VERSION_SUFFIX: ${{ env.VERSION_SUFFIX }}
