# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy docker image - silvestre-blog

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get version from csproj
      id: version
      run: |
        $xml=[xml](Get-Content .\Silvestre.App.Blog.Web.csproj)
        $version=$xml.Project.PropertyGroup.Version
        echo "project_version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh
      working-directory: src/Silvestre.App.Blog.Web
    - name: Set suffix for dev version
      if: github.ref == 'refs/heads/*' && github.ref_name == 'dev'
      id: suffix
      run: |
        echo "version_suffix=dev" >> $env:GITHUB_OUTPUT
      shell: pwsh
      working-directory: src/Silvestre.App.Blog.Web
    - name: Print version
      run: echo "The version is ${{ steps.version.outputs.project_version }}"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/*' && (github.ref_name == 'master' || github.ref_name == 'dev')
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64/v8
        file: src/Silvestre.App.Blog.Web/Dockerfile
        push: ${{ github.ref == 'refs/heads/*' && (github.ref_name == 'master' || github.ref_name == 'dev') }}
        tags: paletas/personal-blog:${{ steps.version.outputs.project_version }}${{ steps.version.outputs.version_suffix }},paletas/personal-blog:$(echo ${{ steps.version.outputs.project_version }} | cut -d. -f1,2)${{ steps.version.outputs.version_suffix }}